apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-api-qa
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: disaster-relief
spec:
  project: default
  source:
    repoURL: https://github.com/ciphernerd11/gitops-aks-microservices.git
    targetRevision: main
    path: kube/qa/alert-api/
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
