apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-generator
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: alert-generator
              image: acrdisasterreliefdev.azurecr.io/alert-generator:8ff6b0c4d0fd865c4523402ee2f7f34ca61d16df
              env:
                - name: API_URL
                  value: "http://alert-api-service:8000/alerts"
          restartPolicy: OnFailure
