apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-generator
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: alert-generator
              image: acrdisasterreliefdev.azurecr.io/alert-generator:1f3f01a9dbd7c0e4473fdfa1773b4fbff616c639
              env:
                - name: API_URL
                  value: "http://alert-api-service:8000/alerts"
          restartPolicy: OnFailure
