apiVersion: batch/v1
kind: CronJob
metadata:
  name: alert-generator
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: alert-generator
              image: acrdisasterreliefdev.azurecr.io/alert-generator:86cc60a0b579c7f6eaa7e42cc9152981ad686891
              env:
                - name: API_URL
                  value: "http://alert-api-service:8000/alerts"
          restartPolicy: OnFailure
