apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alert-api-deployment.yaml
- alert-api-service.yml
- alert-api-ingress.yml

images:
- name: acrdisasterreliefdev.azurecr.io/alert-api
  newName: acrdisasterreliefdev.azurecr.io/alert-api
  newTag: alert-api-b6bd057e
