apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- alert-generator-cronjob.yaml

images:
- name: acrdisasterreliefdev.azurecr.io/alert-generator
  newName: acrdisasterreliefdev.azurecr.io/alert-generator
  newTag: alert-generator-960e3913
