apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../../base/notification-worker
- ../common
images:
- name: acrdisasterreliefdev.azurecr.io/notification-worker
  newName: acrdisasterreliefdev.azurecr.io/notification-worker
  newTag: notification-worker-d645a08b
