apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base/alert-api
# - ../common

images:
  - name: acrdisasterreliefdev.azurecr.io/alert-api
    newName: acrdisasterreliefdev.azurecr.io/alert-api
    newTag: alert-api-d645a08b
