apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa

resources:
- ../../base/notification-worker
- ../common

images:
- name: acrdisasterreliefdev.azurecr.io/notification-worker
  newName: acrdisasterreliefqa.azurecr.io/notification-worker
  newTag: latest
