apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- notification-worker-deployment.yaml
- notification-worker-service.yml

images:
- name: acrdisasterreliefdev.azurecr.io/notification-worker
  newName: acrdisasterreliefdev.azurecr.io/notification-worker
  newTag: notification-worker-db4e2a5f
