apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa

resources:
- ../../base/resource-api
- ../common

images:
- name: acrdisasterreliefdev.azurecr.io/resource-api
  newName: acrdisasterreliefqa.azurecr.io/resource-api
  newTag: resource-api-d9e9259f
