apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: qa
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" 
    keyvaultName: "kv-disasterreliefqa"
    cloudName: ""
    tenantId: "4db0fb37-506e-4401-8aa4-752ee1d1732d"
    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - key: POSTGRES_PASSWORD
          objectName: postgres-password
