apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base/alert-generator
# - ../common
images:
  - name: acrdisasterreliefdev.azurecr.io/alert-generator
    newName: acrdisasterreliefdev.azurecr.io/alert-generator
    newTag: alert-generator-d645a08b
