kind: CronJob
partOf: disaster-relief
schedule: "*/1 * * * *"
concurrencyPolicy: Replace
failedJobsHistoryLimit: 1
image:
  repository: acrdisasterreliefdev.azurecr.io/alert-generator
  tag: alert-generator-9f7138d4
service:
  enabled: false
ingress:
  enabled: false
env:
  - name: API_URL
    value: "http://alert-api-dev-service:8080/alerts"
resources:
  requests:
    cpu: 500m
    memory: 32Mi
  limits:
    cpu: 500m
    memory: 64Mi
