kind: Deployment
partOf: disaster-relief
replicaCount: 1
image:
  repository: acrdisasterreliefdev.azurecr.io/notifications-worker
  tag: notifications-worker-9f7138d4
service:
  enabled: false
ingress:
  enabled: false
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
env:
  - name: ALERT_API_URL
    value: "http://alert-api-dev-service:8080"
  - name: POLL_INTERVAL
    value: "10s"
resources:
  requests: {cpu: 50m, memory: 32Mi}
  limits: {cpu: 200m, memory: 64Mi}
