# Dev values override for frontend.

replicaCount: 1
image:
  tag: frontend-c145ef70
ingress:
  hosts:
    - host: dev.disaster-relief.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: disaster-relief-tls
      hosts:
        - dev.disaster-relief.com
