apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-api-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: disaster-relief
spec:
  project: default
  source:
    repoURL: https://github.com/ciphernerd11/gitops-container-apps-azure.git
    targetRevision: main
    path: helm/microservices
    helm:
      valueFiles:
        - ../../helm/values/dev-values/values-dev-alert-api.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true
