apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource-api-ingress
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/resources"
spec:
  ingressClassName: azure-application-gateway

  tls:
    - hosts:
        - disaster-relief.com
      secretName: disaster-relief-tls

  rules:
    - host: disaster-relief.com
      http:
        paths:
          - path: /api/resources
            pathType: Prefix
            backend:
              service:
                name: resource-api-service
                port:
                  number: 3000
